version: "3.2"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    labels:
     - traefik.enable=true
     - traefik.port=16686
     - traefik.backend=jaeger
     - traefik.frontend.rule=Host:jaeger.docker.localhost
  whoami:
    image: emilevauge/whoami
    labels:
     - traefik.enable=true
     - traefik.port=80
     - traefik.backend=whoami1
     - traefik.frontend.rule=Host:whoami.docker.localhost
  traefik:
    image: traefik:v1.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    ports:
      - 80:80
      - 8080:8080
  hotrod:
    image: jaegertracing/example-hotrod:latest
    command: --jaeger-agent.host-port=jaeger:6831
    labels:
     - traefik.enable=true
     - traefik.port=8080
     - traefik.backend=hotrod
     - traefik.frontend.rule=Host:hotrod.docker.localhost
