version: "3.2"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.17
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    labels:
      traefik.http.routers.jaeger.rule: Host(`jaeger.docker.localhost`)
      traefik.http.routers.jaeger.entrypoints: web
      traefik.http.routers.jaeger.service: jaeger
      traefik.http.services.jaeger.loadbalancer.server.port: 16686
  whoami:
    image: containous/whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.docker.localhost`)
      traefik.http.routers.whoami.entrypoints: web
      traefik.http.routers.whoami.service: whoami
      traefik.http.services.whoami.loadbalancer.server.port: 80
  traefik:
    image: traefik:v2.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    labels:
      traefik.http.routers.dashboard.rule: Host(`dashboard.docker.localhost`)
      traefik.http.routers.dashboard.entrypoints: web
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.services.dashboard.loadbalancer.server.port: 8080
    ports:
      - 80:80
      - 8080:8080
  hotrod:
    image: jaegertracing/example-hotrod:1.17
    command: all
    labels:
      traefik.http.routers.hotrod.rule: Host(`hotrod.docker.localhost`)
      traefik.http.routers.hotrod.entrypoints: web
      traefik.http.routers.hotrod.service: hotrod
      traefik.http.services.hotrod.loadbalancer.server.port: 8080
    environment:
      JAEGER_AGENT_HOST: "jaeger"
      JAEGER_AGENT_PORT: "6831"
